__ACME_ISSUER__

__HTTP_REDIRECT_SERVER__

server {
    server_name __DOMAIN_SLUG__ __DOMAIN__;

    # ssl: https://ssl-config.mozilla.org / intermediate config

    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    __SSL_CERTIFICATE_DIRECTIVES__

    __SSL_INTERMEDIATE_CONFIG__

    # access log doesn't contain IP address
    #access_log off;
    access_log /data/ofm/linux_host/logs_nginx/__DOMAIN_SLUG__-access.jsonl access_json buffer=128k;

    error_log /data/ofm/linux_host/logs_nginx/__DOMAIN_SLUG__-error.log;

    add_header X-Robots-Tag "noindex, nofollow" always;
    __HSTS_DIRECTIVE__

    __DYNAMIC_BLOCKS__

    location /styles/ {
        # trailing slash

        alias /data/ofm/linux_host/assets/styles/ofm/; # trailing slash
        try_files $uri.json =404;

        expires 1d;
        default_type application/json;

        # substitute the domain in the TileJSON
        sub_filter '__TILEJSON_DOMAIN__' '__DOMAIN__';
        sub_filter_once off;
        sub_filter_types '*';

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header Cache-Control public;
        add_header X-Robots-Tag "noindex, nofollow" always;
        add_header Strict-Transport-Security "max-age=63072000" always;

    }

    # catch-all block to deny all other requests
    location / {
        deny all;
        error_log /data/ofm/linux_host/logs_nginx/__DOMAIN_SLUG__-deny.log error;
    }
}
